name: pdoc3 Documentation Builder

on:
  push:
    branches: [ main ]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: python -m pip install pdoc3
      - run: python -m pip install requests #For some reason it doesn’t work without this
      - run: python -m pip install flask
      - run: python -m pdoc -- html src -- html-dir docs
