name: Build and test code

on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
        run: python -m pip install -r requirements.txt
        run: python src/bot.py